// Image generation handler (OpenRouter) — turns a text prompt into a hosted
// image URL.
//
// Two hops, both pure I/O (no prompt authoring, no workflow logic — those
// live in the workflow step that hands this tool its `prompt`):
//   1. Generate: call OpenRouter's chat-completions with the image modality
//      to produce image bytes (model id is config, e.g.
//      google/gemini-2.5-flash-image).
//   2. Host: POST the bytes to the configured media receiver (an
//      OCCA-compatible endpoint, e.g. a site's /api/media) which stores them
//      and answers with `{ url }`. OCCA holds no blob storage of its own, so
//      the publisher hosts its own media — symmetric with the publish tool.
//
// One concrete provider per catalog entry (the X-tool pattern): this is the
// OpenRouter image tool. A different backend (native Gemini, fal, …) would be
// its own catalog entry, not a switch inside here.
//
// The house visual style is locked in `metadata.styleTemplate`: it is prefixed
// to every prompt so a series stays on-brand. The caller only supplies the
// per-image subject.

import crypto from "node:crypto";
import { z } from "zod";
import { childLogger } from "../../../lib/logger";
import { LIMITS } from "../../../lib/limits";
import type { ToolHandler, ToolInvokeResult } from "../domain/types";

const log = childLogger("tools:handlers:image");

const SIGNATURE_HEADER = "X-OCCA-Signature";
const DELIVERY_HEADER = "X-OCCA-Delivery";
const GENERATE_TIMEOUT_MS = 60_000;
const UPLOAD_TIMEOUT_MS = 20_000;
const OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions";
const OPENROUTER_KEY_URL = "https://openrouter.ai/api/v1/key";

const credentialsSchema = z.object({
  apiKey: z.string().min(1).max(LIMITS.API_KEY),
  // The media receiver the generated bytes are POSTed to. Must return { url }.
  uploadEndpoint: z.string().trim().url().max(LIMITS.URL),
  uploadSecret: z.string().min(1).max(LIMITS.WEBHOOK_SECRET),
});
type ImageCredentials = z.infer<typeof credentialsSchema>;

const metadataSchema = z.object({
  // Image model on OpenRouter (e.g. google/gemini-2.5-flash-image).
  model: z
    .string()
    .trim()
    .min(1)
    .max(LIMITS.TITLE)
    .default("google/gemini-2.5-flash-image"),
  // Locked house style, prefixed to every prompt. Empty = caller's prompt
  // verbatim.
  styleTemplate: z.string().trim().max(LIMITS.DESCRIPTION_SHORT).default(""),
  // Soft aspect-ratio hint appended to the prompt (e.g. 16:9). Empty = none.
  aspectRatio: z.string().trim().max(LIMITS.TINY).default(""),
});
type ImageMetadata = z.infer<typeof metadataSchema>;

const generateInputSchema = z.object({
  // A visual concept, not a title — allow up to a full description's worth of
  // text. (The cover brief runs a couple of sentences; a tight TITLE cap was
  // too small, so this is generous headroom while still capping a runaway.)
  prompt: z.string().trim().min(1).max(LIMITS.DESCRIPTION),
});

const generateOutputSchema = z.object({ url: z.string().url() });

function sign(body: string, secret: string): string {
  return crypto.createHmac("sha256", secret).update(body).digest("hex");
}

// Parse a data URL ("data:image/png;base64,AAAA") into bytes + mime.
function parseDataUrl(
  url: string,
): { dataBase64: string; mimeType: string } | null {
  const m = url.match(/^data:([^;]+);base64,(.+)$/);
  if (!m) return null;
  return { mimeType: m[1]!, dataBase64: m[2]! };
}

// Generate via OpenRouter chat-completions with the image modality. The image
// comes back as a base64 data URL at choices[0].message.images[0].image_url.url.
async function generateImage(
  creds: ImageCredentials,
  meta: ImageMetadata,
  fullPrompt: string,
): Promise<
  | { ok: true; dataBase64: string; mimeType: string }
  | { ok: false; errorCode: string; errorMessage: string; rateLimited?: boolean }
> {
  const body = JSON.stringify({
    model: meta.model,
    messages: [{ role: "user", content: fullPrompt }],
    modalities: ["image", "text"],
  });

  let res: Response;
  try {
    res = await fetch(OPENROUTER_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${creds.apiKey}`,
      },
      body,
      signal: AbortSignal.timeout(GENERATE_TIMEOUT_MS),
    });
  } catch (err) {
    return {
      ok: false,
      errorCode: "network_error",
      errorMessage: err instanceof Error ? err.message : "image generation request failed",
    };
  }

  const text = await res.text().catch(() => "");
  if (res.status === 429) {
    return { ok: false, errorCode: "rate_limited", errorMessage: text.slice(0, 400) || "Model rate limited.", rateLimited: true };
  }
  if (!res.ok) {
    return { ok: false, errorCode: `generate_${res.status}`, errorMessage: text.slice(0, 400) || `Model returned ${res.status}` };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    return { ok: false, errorCode: "bad_response", errorMessage: "Model returned non-JSON." };
  }
  const url = (
    parsed as {
      choices?: { message?: { images?: { image_url?: { url?: string } }[] } }[];
    }
  )?.choices?.[0]?.message?.images?.[0]?.image_url?.url;
  if (!url) return { ok: false, errorCode: "no_image", errorMessage: "Response contained no image." };
  const image = parseDataUrl(url);
  if (!image) return { ok: false, errorCode: "bad_image", errorMessage: "Image was not a base64 data URL." };
  return { ok: true, ...image };
}

// Host the bytes on the configured media receiver, returning its public URL.
async function uploadImage(
  creds: ImageCredentials,
  dataBase64: string,
  mimeType: string,
): Promise<ToolInvokeResult> {
  const payload = JSON.stringify({ dataBase64, mimeType });
  const signature = sign(payload, creds.uploadSecret);

  let res: Response;
  try {
    res = await fetch(creds.uploadEndpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        [SIGNATURE_HEADER]: `sha256=${signature}`,
        [DELIVERY_HEADER]: crypto.randomUUID(),
      },
      body: payload,
      signal: AbortSignal.timeout(UPLOAD_TIMEOUT_MS),
    });
  } catch (err) {
    return { ok: false, errorCode: "network_error", errorMessage: err instanceof Error ? err.message : "media upload failed" };
  }

  const text = await res.text().catch(() => "");
  if (!res.ok) {
    return { ok: false, errorCode: `upload_${res.status}`, errorMessage: text.slice(0, 300) || `Media receiver returned ${res.status}` };
  }

  let url: string | null = null;
  try {
    const parsed = JSON.parse(text) as { url?: unknown };
    if (typeof parsed.url === "string" && parsed.url.length > 0) url = parsed.url;
  } catch {
    /* non-JSON */
  }
  if (!url) {
    return { ok: false, errorCode: "no_url_returned", errorMessage: "Media receiver accepted the image but did not return a { url }." };
  }
  return { ok: true, output: { url }, resultSummary: { url } };
}

export const imageHandler: ToolHandler = {
  type: "image",
  displayName: "Image generation (OpenRouter)",
  description:
    "Generate an image from a text prompt via OpenRouter and get back its hosted public URL. House style is locked in config; the caller supplies only the subject.",
  credentialsSchema,
  credentialFields: [
    {
      name: "apiKey",
      type: "string",
      required: true,
      secret: true,
      description: "OpenRouter API key used to generate the image.",
    },
    {
      name: "uploadEndpoint",
      type: "string",
      required: true,
      secret: false,
      description: "The media receiver the generated bytes are POSTed to. Must return { url }.",
    },
    {
      name: "uploadSecret",
      type: "string",
      required: true,
      secret: true,
      description: "Shared secret used to HMAC-sign the upload request.",
    },
  ],
  metadataSchema,
  metadataFields: [
    {
      name: "model",
      type: "string",
      required: false,
      secret: false,
      description: "OpenRouter image model (default google/gemini-2.5-flash-image).",
    },
    {
      name: "styleTemplate",
      type: "string",
      required: false,
      secret: false,
      description: "Locked house style, prefixed to every prompt so a series stays on-brand.",
    },
    {
      name: "aspectRatio",
      type: "string",
      required: false,
      secret: false,
      description: "Aspect ratio hint appended to the prompt, e.g. 16:9.",
    },
  ],
  actions: {
    generate: {
      name: "generate",
      description: "Generate an image for a subject and return its hosted public URL.",
      inputSchema: generateInputSchema,
      outputSchema: generateOutputSchema,
      invoke: async (ctx, input): Promise<ToolInvokeResult> => {
        const parsedInput = generateInputSchema.safeParse(input);
        if (!parsedInput.success) {
          return { ok: false, errorCode: "invalid_input", errorMessage: parsedInput.error.message };
        }
        const creds = ctx.credentials as ImageCredentials;
        const meta = metadataSchema.parse(ctx.metadata ?? {});
        const parts = [
          meta.styleTemplate,
          `Subject for this image: ${parsedInput.data.prompt}`,
          meta.aspectRatio ? `Use a ${meta.aspectRatio} aspect ratio.` : "",
        ].filter(Boolean);
        const fullPrompt = parts.join("\n\n");

        const generated = await generateImage(creds, meta, fullPrompt);
        if (!generated.ok) {
          log.warn({ errorCode: generated.errorCode }, "image generation failed");
          return generated;
        }
        return uploadImage(creds, generated.dataBase64, generated.mimeType);
      },
    },
  },
  // Cheap reachability/key check: OpenRouter's key endpoint validates the key
  // without spending a generation.
  testConnection: async ({ credentials }) => {
    const parsed = credentialsSchema.safeParse(credentials);
    if (!parsed.success) {
      return { ok: false, errorCode: "invalid_credentials_shape", errorMessage: parsed.error.message };
    }
    try {
      const res = await fetch(OPENROUTER_KEY_URL, {
        method: "GET",
        headers: { Authorization: `Bearer ${parsed.data.apiKey}` },
        signal: AbortSignal.timeout(UPLOAD_TIMEOUT_MS),
      });
      if (!res.ok) {
        return { ok: false, errorCode: `key_${res.status}`, errorMessage: `OpenRouter returned ${res.status}` };
      }
      return { ok: true, detail: "OpenRouter API key valid. (Media upload endpoint not exercised by this test.)" };
    } catch (err) {
      return { ok: false, errorCode: "network_error", errorMessage: err instanceof Error ? err.message : "image test failed" };
    }
  },
};
