// Image generation handler — turns a text prompt into a hosted image URL.
//
// Two hops, both pure I/O (no prompt authoring, no workflow logic — those
// live in the workflow step that hands this tool its `prompt`):
//   1. Generate: call the configured model (Gemini "Nano Banana"
//      gemini-2.5-flash-image by default) to produce image bytes.
//   2. Host: POST the bytes to the configured media receiver (an
//      OCCA-compatible endpoint, e.g. a site's /api/media) which stores them
//      and answers with `{ url }`. OCCA holds no blob storage of its own, so
//      the publisher hosts its own media — symmetric with the publish tool.
//
// The house visual style is locked in `metadata.styleTemplate`: it is prefixed
// to every prompt so a series stays on-brand. The caller only supplies the
// per-image subject.

import crypto from "node:crypto";
import { z } from "zod";
import { childLogger } from "../../../lib/logger";
import { LIMITS } from "../../../lib/limits";
import type { ToolHandler, ToolInvokeResult } from "../domain/types";

const log = childLogger("tools:handlers:image");

const SIGNATURE_HEADER = "X-OCCA-Signature";
const DELIVERY_HEADER = "X-OCCA-Delivery";
const GENERATE_TIMEOUT_MS = 60_000;
const UPLOAD_TIMEOUT_MS = 20_000;
const GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta/models";

const credentialsSchema = z.object({
  geminiApiKey: z.string().min(1).max(LIMITS.URL),
  // The media receiver the generated bytes are POSTed to. Must return { url }.
  uploadEndpoint: z.string().trim().url().max(LIMITS.URL),
  uploadSecret: z.string().min(1).max(LIMITS.WEBHOOK_SECRET),
});
type ImageCredentials = z.infer<typeof credentialsSchema>;

const metadataSchema = z.object({
  // Model id on the Generative Language API. Default is Nano Banana.
  model: z.string().trim().min(1).max(LIMITS.TINY).default("gemini-2.5-flash-image"),
  // Locked house style, prefixed to every prompt. Empty = caller's prompt
  // verbatim.
  styleTemplate: z.string().trim().max(LIMITS.TITLE).default(""),
  // Passed through to the model's aspect-ratio control (e.g. "16:9" for a
  // wide article thumbnail). Empty = model default.
  aspectRatio: z.string().trim().max(LIMITS.TINY).default(""),
});
type ImageMetadata = z.infer<typeof metadataSchema>;

const generateInputSchema = z.object({
  prompt: z.string().trim().min(1).max(LIMITS.TITLE),
});

const generateOutputSchema = z.object({ url: z.string().url() });

function sign(body: string, secret: string): string {
  return crypto.createHmac("sha256", secret).update(body).digest("hex");
}

// Pull the first inline image part out of a generateContent response. The API
// returns base64 in `candidates[].content.parts[].inlineData` (camelCase on
// v1beta; snake_case `inline_data` on some versions) — accept either.
function extractImage(
  json: unknown,
): { dataBase64: string; mimeType: string } | null {
  const candidates = (json as { candidates?: unknown[] })?.candidates;
  if (!Array.isArray(candidates)) return null;
  for (const c of candidates) {
    const parts = (c as { content?: { parts?: unknown[] } })?.content?.parts;
    if (!Array.isArray(parts)) continue;
    for (const p of parts) {
      const inline =
        (p as { inlineData?: { data?: string; mimeType?: string } }).inlineData ??
        (p as { inline_data?: { data?: string; mime_type?: string } }).inline_data;
      const dataBase64 = (inline as { data?: string })?.data;
      const mimeType =
        (inline as { mimeType?: string })?.mimeType ??
        (inline as { mime_type?: string })?.mime_type;
      if (dataBase64) {
        return { dataBase64, mimeType: mimeType ?? "image/png" };
      }
    }
  }
  return null;
}

// Call the model and return the raw image bytes (base64 + mime).
async function generateImage(
  creds: ImageCredentials,
  meta: ImageMetadata,
  prompt: string,
): Promise<
  | { ok: true; dataBase64: string; mimeType: string }
  | { ok: false; errorCode: string; errorMessage: string; rateLimited?: boolean }
> {
  const fullPrompt = meta.styleTemplate
    ? `${meta.styleTemplate}\n\nSubject for this image: ${prompt}`
    : prompt;

  const body = JSON.stringify({
    contents: [{ parts: [{ text: fullPrompt }] }],
    generationConfig: {
      responseModalities: ["TEXT", "IMAGE"],
      ...(meta.aspectRatio
        ? { imageConfig: { aspectRatio: meta.aspectRatio } }
        : {}),
    },
  });

  let res: Response;
  try {
    res = await fetch(`${GEMINI_BASE}/${meta.model}:generateContent`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-goog-api-key": creds.geminiApiKey,
      },
      body,
      signal: AbortSignal.timeout(GENERATE_TIMEOUT_MS),
    });
  } catch (err) {
    return {
      ok: false,
      errorCode: "network_error",
      errorMessage: err instanceof Error ? err.message : "image generation request failed",
    };
  }

  const text = await res.text().catch(() => "");
  if (res.status === 429) {
    return { ok: false, errorCode: "rate_limited", errorMessage: "Model rate limited.", rateLimited: true };
  }
  if (!res.ok) {
    return {
      ok: false,
      errorCode: `generate_${res.status}`,
      errorMessage: text.slice(0, 300) || `Model returned ${res.status}`,
    };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    return { ok: false, errorCode: "bad_response", errorMessage: "Model returned non-JSON." };
  }
  const image = extractImage(parsed);
  if (!image) {
    return { ok: false, errorCode: "no_image", errorMessage: "Model response contained no image." };
  }
  return { ok: true, ...image };
}

// Host the bytes on the configured media receiver, returning its public URL.
async function uploadImage(
  creds: ImageCredentials,
  dataBase64: string,
  mimeType: string,
): Promise<ToolInvokeResult> {
  const payload = JSON.stringify({ dataBase64, mimeType });
  const signature = sign(payload, creds.uploadSecret);

  let res: Response;
  try {
    res = await fetch(creds.uploadEndpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        [SIGNATURE_HEADER]: `sha256=${signature}`,
        [DELIVERY_HEADER]: crypto.randomUUID(),
      },
      body: payload,
      signal: AbortSignal.timeout(UPLOAD_TIMEOUT_MS),
    });
  } catch (err) {
    return {
      ok: false,
      errorCode: "network_error",
      errorMessage: err instanceof Error ? err.message : "media upload failed",
    };
  }

  const text = await res.text().catch(() => "");
  if (!res.ok) {
    return {
      ok: false,
      errorCode: `upload_${res.status}`,
      errorMessage: text.slice(0, 300) || `Media receiver returned ${res.status}`,
    };
  }

  let url: string | null = null;
  try {
    const parsed = JSON.parse(text) as { url?: unknown };
    if (typeof parsed.url === "string" && parsed.url.length > 0) url = parsed.url;
  } catch {
    /* non-JSON */
  }
  if (!url) {
    return {
      ok: false,
      errorCode: "no_url_returned",
      errorMessage: "Media receiver accepted the image but did not return a { url }.",
    };
  }
  return { ok: true, output: { url }, resultSummary: { url } };
}

export const imageHandler: ToolHandler = {
  type: "image",
  displayName: "Image generation",
  description:
    "Generate an image from a text prompt and get back its hosted public URL. The house style is locked in config; the caller supplies only the subject.",
  credentialsSchema,
  credentialFields: [
    {
      name: "geminiApiKey",
      type: "string",
      required: true,
      secret: true,
      description: "Google Generative Language API key used to generate the image.",
    },
    {
      name: "uploadEndpoint",
      type: "string",
      required: true,
      secret: false,
      description: "The media receiver the generated bytes are POSTed to. Must return { url }.",
    },
    {
      name: "uploadSecret",
      type: "string",
      required: true,
      secret: true,
      description: "Shared secret used to HMAC-sign the upload request.",
    },
  ],
  metadataSchema,
  metadataFields: [
    {
      name: "model",
      type: "string",
      required: false,
      secret: false,
      description: "Model id (default gemini-2.5-flash-image, a.k.a. Nano Banana).",
    },
    {
      name: "styleTemplate",
      type: "string",
      required: false,
      secret: false,
      description: "Locked house style, prefixed to every prompt so a series stays on-brand.",
    },
    {
      name: "aspectRatio",
      type: "string",
      required: false,
      secret: false,
      description: "Aspect ratio for the image, e.g. 16:9 for a wide thumbnail.",
    },
  ],
  actions: {
    generate: {
      name: "generate",
      description: "Generate an image for a subject and return its hosted public URL.",
      inputSchema: generateInputSchema,
      outputSchema: generateOutputSchema,
      invoke: async (ctx, input): Promise<ToolInvokeResult> => {
        const parsedInput = generateInputSchema.safeParse(input);
        if (!parsedInput.success) {
          return { ok: false, errorCode: "invalid_input", errorMessage: parsedInput.error.message };
        }
        const creds = ctx.credentials as ImageCredentials;
        const meta = metadataSchema.parse(ctx.metadata ?? {});

        const generated = await generateImage(creds, meta, parsedInput.data.prompt);
        if (!generated.ok) {
          log.warn({ errorCode: generated.errorCode }, "image generation failed");
          return generated;
        }
        return uploadImage(creds, generated.dataBase64, generated.mimeType);
      },
    },
  },
  // Cheap reachability/key check: list models with the configured key. Avoids
  // spending a generation on every connection test.
  testConnection: async ({ credentials }) => {
    const parsed = credentialsSchema.safeParse(credentials);
    if (!parsed.success) {
      return { ok: false, errorCode: "invalid_credentials_shape", errorMessage: parsed.error.message };
    }
    try {
      const res = await fetch("https://generativelanguage.googleapis.com/v1beta/models", {
        method: "GET",
        headers: { "x-goog-api-key": parsed.data.geminiApiKey },
        signal: AbortSignal.timeout(UPLOAD_TIMEOUT_MS),
      });
      if (!res.ok) {
        return { ok: false, errorCode: `models_${res.status}`, errorMessage: `Model API returned ${res.status}` };
      }
      return { ok: true, detail: "Gemini API key valid. (Media upload endpoint not exercised by this test.)" };
    } catch (err) {
      return {
        ok: false,
        errorCode: "network_error",
        errorMessage: err instanceof Error ? err.message : "image test failed",
      };
    }
  },
};
